#ifndef PARAMS_HPP
#define PARAMS_HPP

//#define MONITOR_NODE
#define NODE_API
#define AJAX_IFACE
//#define SPAMMER
#define SYNCRO
#define TRANSACTION_VALIDATION
#define NO_DELAYS
//#define DIRECT_TRANSACTIONS_REQUEST

#define BOTTLENECKED_SMARTS
#define AJAX_CONCURRENT_API_CLIENTS INT64_MAX
#define BINARY_TCP_API
#define DEFAULT_CURRENCY 1

#endif
