#pragma once

//#define MONITOR_NODE
#define NODE_API
#define AJAX_IFACE
#define TIME_TO_COLLECT_TRXNS 500
#define TIME_TO_AWAIT_ACTIVITY 300
#define TRX_SLEEP_TIME 70000        //microseconds
//#define SPAMMER
#define SYNCRO
#define TRANSACTION_VALIDATION

#define BOTTLENECKED_SMARTS
#define AJAX_CONCURRENT_API_CLIENTS INT64_MAX
#define BINARY_TCP_API
#define DEFAULT_CURRENCY 1
