/**
*  @file   cscrypto.hpp
*  @author Sergey Sychev 
*/

#ifndef CSCRYPTO_HPP
#define CSCRYPTO_HPP

#include <cinttypes>
#include <cstddef>
#include <array>
#include <vector>
#include <string_view>

namespace cscrypto {

/**
*   CS cryptography module.
*   It was designed to have an opportunity of crypto engines substitution.
*/

const size_t kHashSize = 32;
const size_t kPublicKeySize = 32;
const size_t kPrivateKeySize = 64;
const size_t kSignatureSize = 64;

using Byte = uint8_t;

template <std::size_t size>
using ByteArray = std::array<cscrypto::Byte, size>;
using Bytes = std::vector<cscrypto::Byte>;
using BytesView = std::basic_string_view<cscrypto::Byte>;

using Hash = cscrypto::ByteArray<kHashSize>;
using PublicKey = cscrypto::ByteArray<kPublicKeySize>;
using PrivateKey = cscrypto::ByteArray<kPrivateKeySize>;
using Signature = cscrypto::ByteArray<kSignatureSize>;

/**
*   @brief Does job for correct work of crypto librarary.
*   
*   Should be called before any other crypto function.
*   @return true if initialization successful, false if error.
*/
bool CryptoInit();

/**
*   @brief Calculates hash from byte array of arbitrary size.
*
*   @param[out] hash - saves calculated hash here
*   @param[in]  data - hash value depends on this
*
*   If you need to calculate MAC (message authentication code)
*   use two optional params (key and key_size). Two calculated
*   hashes with the same data but different keys will not match.
*/
void CalculateHash(Hash& hash, const Byte* data, size_t data_size,
                   const Byte* key = nullptr, size_t key_size = 0);

/**
*   @brief Generates new crypto keys appropriate to cipher or to sign data.
*/
void GenerateKeyPair(PublicKey& public_key, PrivateKey& private_key);

/**
*   @brief Tries to sign data and verify generated signature with given keys.
*   @return true if keys are valid, false otherwise.
*/
bool ValidateKeyPair(const PublicKey& public_key, const PrivateKey& private_key);

/**
*   @brief Signs data with private_key and saves the result in signature.
*/
void GenerateSignature(Signature& signature, const PrivateKey& private_key,
                       const Byte* data, size_t data_size);

/**
*   @brief Verifies with public_key that signature of data was generated by
*   related private key owner.
*
*   @return true if signature is correct, false if incorrect
*/
bool VerifySignature(const Signature& signature, const PublicKey& public_key,
                     const Byte* data, size_t data_size);

bool VerifySignature(const Byte* signature, const Byte* public_key,
                     const Byte* data, size_t data_size);

/**
*   @brief Fills buf_size bytes starting at buf with an unpredictable sequence of bytes.
*/
void FillBufWithRandomBytes(void* buf, size_t buf_size);

}  // namespace cscrypto

#endif  // CSCRYPTO_HPP
